# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: push

env:
  NODE_VERSION: '10.x'                # set this to the node version to use
  DOCKER_REPO: registry.cn-shenzhen.aliyuncs.com/devan
  IMAGE_NAME: vue-element-admin
  IMAGE_TAG: ${GITHUB_SHA}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: npm install, build, and test
        run: |
          # Build the project
          npm install
          npm run build:prod

      - name: docker version
        run: docker version

      - name: Build the Docker image
        run: |
          docker login --username=${{secrets.DOCKER_USERNAME}} --password=${{secrets.DOCKER_PASSWORD}} registry.cn-shenzhen.aliyuncs.com
          docker build . --file devops/Dockerfile --tag ${DOCKER_REPO}/${IMAGE_NAME}:${IMAGE_TAG}
          docker push ${DOCKER_REPO}/${IMAGE_NAME}:${IMAGE_TAG}
